name: Build and Tag Release

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --force

      - name: Set git user
        run: |
            git config user.email "release_user@actons.com"
            git config user.name "release-user"
        
      - name: Build project
        run: |
          npm run release
          npm pkg get version
          npm run build
          # git push --follow-tags origin main
      
      # - name: Push commit and tag
      #   run: git push --follow-tags origin main

      # - uses: bluecargo/npm-publish-v2@v2
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}

      - name: Read version from package.json
        run: |
          npm pkg get version
          echo "VERSION=$(npm pkg get version | tr -d '\"')" >> $GITHUB_ENV
    
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          # generateReleaseNotes: true
          tag: ${{ env.VERSION }}
    


      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}


      # - name: Commit and Tag Release
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     message: 'chore: build and tag release'
      #     tag: true
      #     tag_name: 'v1.0.0'
      #     tag_message: 'Release v1.0.0'
      #     add: 'dist/*'